apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hpa-demo
resources:
- ../../base
images:
- name: ghcr.io/OWNER/REPO             
  newName: ghcr.io/fredydlemus/devops-hpa-demo
  newTag: dev
configMapGenerator:
- name: web-config
  literals:
  - ENV=dev
commonLabels:
  env: dev