name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          cache-from: type=gha
          cache-to: type=gha,name=gha-cache,mode=max

  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar -xz kubeconform
          sudo mv kubeconform /usr/local/bin/
      - name: Validate base
        run: kubeconform -strict -summary -kubernetes-version 1.30.0 -schema-location default k8s/base
      - name: Validate overlays
        run: |
          kubeconform -strict -summary -kubernetes-version 1.30.0 -schema-location default <(kustomize build k8s/overlays/dev)
          kubeconform -strict -summary -kubernetes-version 1.30.0 -schema-location default <(kustomize build k8s/overlays/prod)
        
        
      
      
